categories:
  otIconselector:

settings:
  otIconselector.favorites.default:
    category: otIconselector
    type: string
    default: ''

  otIconselector.favorites.buttons:
    category: otIconselector
    type: string
    default: ''
